Exercise 3 (wip)
chengjoanna1729/DevOps-Course-Starter pull request #3
Opened 2020-07-22 21:22 UTC by chengjoanna1729

still to add more selenium tests

2020-08-03 15:44 UTC, Jonesey13 commented
In order to pass this Module's project exercise you're going to need to add:

1. Documentation on how to connect this project up to someone's trello board
1. Document how to run the tests
1. Add all necessary dependencies such as selenium & pytest

2020-08-03 15:59 UTC, Jonesey13 requested changes
OK I've reviewed the code as well. We'll need some interactive Selenium behaviour as well. Other comments are really just minor.

2020-08-03 15:59 UTC, Jonesey13 commented on tests/test_app.py
> +    assert 'A name for an item' in html_string
You'll ideally want a more targeted inspection here (e.g. using xpath)

2020-08-03 15:59 UTC, Jonesey13 commented on tests/test_view_model.py
> +    assert set([item.id for item in to_do_items]) == set([1, 2])
Wouldn't a simple list comparison work here?

2020-08-03 15:59 UTC, Jonesey13 commented on tests/test_view_model.py
> +    assert doing_items[0].id == 3
Same here and below

2020-08-03 15:59 UTC, Jonesey13 commented on tests_e2e/test_app.py
> +    # TODO: assert more things
Yes we should definitely do some interactive here

2020-09-17 12:19 UTC, hugh-emerson requested changes
Ah, sorry it looks like I reviewed this a while ago but didn't actually click submit review...

If you just fix my comment on the create_app function definition, then you can merge this.

I've also left some other suggestions.

2020-09-17 12:19 UTC, hugh-emerson commented on README.md
> +To run tests in a particular folder, run `pytest tests` or `pytest tests_e2e`.
You should mention that the e2e tests require Firefox and geckodriver

2020-09-17 12:19 UTC, hugh-emerson commented on README.md
> +To connect up the app with a trello board, copy the contents of `.env.test` into a `.env` file.
Actually, there's already a .env.template file that automatically gets copied into .env the first time you run setup. And you should stick to using that as the template instead of copying from .env.test, because there might be other customisations to the env file for testing purposes (like `FLASK_SKIP_DOTENV=True`)

2020-09-17 12:19 UTC, hugh-emerson commented on app.py
> +def create_app(dotenv):
This works with the tests, but does `flask run` still work for you? If I do that, it says this `dotenv` is a ScriptInfo object, but you're expecting it to be a string?

Giving it a default value seems to fix it.

2020-09-17 12:19 UTC, hugh-emerson commented on app.py
> +        app.run()
You can delete this.

2020-09-17 12:19 UTC, hugh-emerson commented on tests/test_app.py
> +    assert all(item_name in ('A name for an item', 'Eat lunch', 'Finish exercise') for item_name in tree.xpath("//span/text()"))
Did you get this the wrong way around?

Looks like you're asserting that the text of every span on the page is one of ['A name for an item', 'Eat lunch', 'Finish exercise'].
Which is not robust for two main reasons:
- if  tree.xpath("//span/text()") returns an empty list, the test passes
- if an unrelated span is anywhere on the page, the test fails

For the first point, did you mean to assert that all of the expected item names are in a span on the page?
Easiest way is to do `['A name for an item', 'Eat lunch', 'Finish exercise'] == tree.xpath("//span/text()")`
You can wrap the lists in set([...]) if you don't care about ordering.

For the second point, it's nicer to find the elements by a class name rather than tag name.

2020-09-17 12:19 UTC, hugh-emerson commented on app.py
> +def create_app(dotenv):
Apart from that, what did you mean by "I don't think the test app is able to read .env.test properly,"?

You can stick a breakpoint in trello.py, run the integration test in debug mode and you'll see the config does have the test values.

Regarding "but the mocked requests mean that it doesn't call trello anyway?" - yes, but it's good practice to use .env.test for two reasons:
Mainly so you don't accidentally make real API calls with values from .env. Say, during dev you add a new test and forget to include your mock requests fixture (which should probably have autouse=true), but you think everything's fine because it passes (because it makes a real but successful request)

Secondly, your tests could assert things like the API request has key=expected-value.

2020-09-17 12:19 UTC, hugh-emerson commented on tests/test_app.py
> +def mock_get_requests(monkeypatch):
Name is misleading - this doesn't just mock get requests, this mocks any call to `requests.request`

2020-09-24 14:02 UTC, chengjoanna1729 commented on app.py
> +def create_app(dotenv):
ah i see what the problem was - I've edited my `.env` file so the `FLASK_APP` command is `FLASK_APP=app:create_app('.env')` but this isn't checked in - should I be put this somewhere else

2020-09-24 14:42 UTC, merged